from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv()) 
# This loads the environment variables from a .env file located in the project directory. The find_dotenv() function helps locate the .env file regardless of where the script is run from, making it more flexible and portable. This allows us to securely store sensitive information like API keys without hardcoding them into our code.

from tools.search_api import fetch_macro_news
from tools.market_api import fetch_live_metrics
from agents.sentiment_node import analyze_news_sentiment

state = {
    "market_data": {}, 
    # This dictionary will hold the latest market metrics fetched from the financial APIs. 
    # It will store key-value pairs where the keys are descriptive names of the metrics (e.g., "gold_price", "dxy_change") and the values are the corresponding data points. 
    # This allows us to easily access and display the most recent market information in our application.
    "raw_news": "", 
    # This string will hold the raw news headlines fetched from the DuckDuckGo Search API. 
    # It will contain the latest macroeconomic news headlines that are relevant to gold, inflation, and the global economy.
    "sentiment_score": 0.0,
    # This float will hold the sentiment score calculated from the fetched news headlines.
    # The sentiment score is a numerical representation of the overall sentiment expressed in the news articles (e.g., positive, negative, or neutral).
    "ml_prediction": "",
    # This string will hold the prediction generated by the machine learning model based on the market data and sentiment analysis.
    # The prediction could be a simple label (e.g., "Bullish", "Bearish", "Neutral") or a more detailed description of the expected market trend for gold.
    "final_report": "",
    # This string will hold the final report generated by the application, which combines the market data, sentiment analysis, and machine learning prediction into a comprehensive summary.
}


def execute_data_pipeline():
    """
    Executes the data pipeline to fetch market metrics and macroeconomic news.
    """
    # Fetch live market metrics
    print("1. Fetching live market metrics...")
    state["market_data"] = fetch_live_metrics()
    print(f"   Gold Price: ${state['market_data'].get('gold_price', 'N/A')}\n")
    # This function call retrieves the latest market metrics (e.g., gold price, DXY index, oil price, treasury yield) and stores them in the state dictionary under the "market_data" key.

    # Fetch macroeconomic news headlines
    print("2. Fetching macroeconomic news...")
    state["raw_news"] = fetch_macro_news()      # This function call retrieves the latest macroeconomic news headlines related to gold and inflation and stores them in the state dictionary under the "raw_news" key.
    print(f"   Successfully loaded {len(state['raw_news'])} news signals.\n")   


    print("3. Executing sentiment Agent analysis...")
    sentiment_result = analyze_news_sentiment(state["raw_news"])
    state["sentiment_score"] = sentiment_result.get("score", 0.0)
    state["sentiment_rationale"] = sentiment_result.get("rationale", "No rationale provided.") 
    # This function call analyzes the sentiment of the fetched news headlines and updates the state dictionary with the resulting sentiment score and rationale.
    #0.0 and "No rationale provided." are fallback values in case the sentiment analysis fails or does not return a rationale.

    print(f"   Sentiment Score: {state['sentiment_score']}\n")
    print(f"   Sentiment Rationale: {state['sentiment_rationale']}\n")

    print("✅ Data pipeline execution complete.")

    
if __name__ == "__main__":
    execute_data_pipeline()